// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20PausableUpgradeable$Type } from "./ERC20PausableUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20PausableUpgradeable"]: ERC20PausableUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/token/ERC20/extensions/ERC20PausableUpgradeable.sol:ERC20PausableUpgradeable"]: ERC20PausableUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["ERC20PausableUpgradeable"]: GetContractReturnType<ERC20PausableUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/token/ERC20/extensions/ERC20PausableUpgradeable.sol:ERC20PausableUpgradeable"]: GetContractReturnType<ERC20PausableUpgradeable$Type["abi"]>;
  }
}
