// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { XIdrToken$Type } from "./XIdrToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["XIdrToken"]: XIdrToken$Type;
    ["contracts/XIdrToken.sol:XIdrToken"]: XIdrToken$Type;
  }

  interface ContractTypesMap {
    ["XIdrToken"]: GetContractReturnType<XIdrToken$Type["abi"]>;
    ["contracts/XIdrToken.sol:XIdrToken"]: GetContractReturnType<XIdrToken$Type["abi"]>;
  }
}
