// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20BurnableUpgradeable$Type } from "./ERC20BurnableUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20BurnableUpgradeable"]: ERC20BurnableUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/token/ERC20/extensions/ERC20BurnableUpgradeable.sol:ERC20BurnableUpgradeable"]: ERC20BurnableUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["ERC20BurnableUpgradeable"]: GetContractReturnType<ERC20BurnableUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/token/ERC20/extensions/ERC20BurnableUpgradeable.sol:ERC20BurnableUpgradeable"]: GetContractReturnType<ERC20BurnableUpgradeable$Type["abi"]>;
  }
}
